### ISSUE TITLE
Host not found in upstream "frontend:8885" about demo

### ISSUE THREAD

**Issue by xcaspar** [alibaba/Appactive#3]
**Describe the bug**

```
nginx: [emerg] host not found in upstream "frontend:8885" in /etc/nginx/conf/apps/example.conf:32
```

**To Reproduce**
Follow the steps in the readme.

**Expected behavior**
Accessing the page succeeded, not 502.

**Screenshots**
![image](https://user-images.githubusercontent.com/3992234/148891740-46a6d5f1-e3d9-4efe-ae65-cc4868696923.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by njtukang** [comment]
run sh run-nacos-quick.sh instead

**Comment by njtukang** [comment]
run “sh run-nacos-quick.sh” instead
