### ISSUE TITLE
调用set接口推送路由规则的时候错误

### ISSUE THREAD

**Issue by yahuaChen** [alibaba/Appactive#9]
我在Mac上调试gateway，基于OpenResty加载了Gateway的Lua脚本，在调用set接口推送路由规则的时候，报了个错误，但实际规则已经写到store了

![image](https://user-images.githubusercontent.com/23414909/176121422-c4d22cee-83b1-41ca-ad7a-07cac5dac2ed.png)

**Comment by yahuaChen** [comment]
openresty  1.21.4.1_1

**Comment by yahuaChen** [comment]
2022/06/28 15:17:54 [error] 6057#140671: *1 lua entry thread aborted: runtime error: ...Cellar/openresty/1.21.4.1_1/lualib/resty/core/shdict.lua:320: NYI: cannot call this C function (yet)
stack traceback:
coroutine 0:
	[C]: in function 'ngx_lua_ffi_shdict_get'
	...Cellar/openresty/1.21.4.1_1/lualib/resty/core/shdict.lua:320: in function 'get'
	...Cellar/openresty/1.21.4.1_1/nginx/conf/lua/kv/kv_set.lua:37: in main chunk, client: 127.0.0.1, server: , request: "POST /set HTTP/1.1", host: "127.0.0.1:8090"

**Comment by MageekChiu** [comment]
Openresty it`s  self is not compatible with Apple Silicon yet.

You can either wait for next version of openresty or build it yourselves or just use another OS  .
